/* GENERATED by scripts/build-tokens.mjs from tokens/core/motion.json — DO NOT EDIT. */

export const SPRING_TOKENS = {
  "window": {
    "stiffness": 480,
    "damping": 34,
    "mass": 0.7
  },
  "deck": {
    "stiffness": 500,
    "damping": 34
  },
  "mini": {
    "stiffness": 340,
    "damping": 28
  },
  "zoom": {
    "stiffness": 300,
    "damping": 28
  },
  "widget": {
    "stiffness": 300,
    "damping": 30
  },
  "rise": {
    "stiffness": 300,
    "damping": 20
  },
  "flight": {
    "stiffness": 260,
    "damping": 26
  }
} as const

export const DURATION_TOKENS = {
  "tap": "0.16s",
  "fade": "0.18s",
  "theme": "0.25s",
  "slow": "0.7s"
} as const
