/* Design-token build — Style Dictionary v4 + Tokens Studio transforms.
 * Source of truth: tokens/ (Tokens Studio / DTCG JSON). One SD run per theme
 * from tokens/$themes.json; each theme emits ONLY its `enabled` sets (so
 * classic-dark is a lean override block) while `source` sets resolve refs.
 * outputReferencesFilter keeps var(--blue)/var(--ink) for EMITTED tokens (so
 * the component-scoped --blue pins still cascade into --focus) and resolves
 * references to internal primitives (core/color) down to literals.
 * Output → src/styles/tokens.generated.css (committed; do not hand-edit).
 */
import StyleDictionary from 'style-dictionary'
import { outputReferencesFilter } from 'style-dictionary/utils'
import { register } from '@tokens-studio/sd-transforms'
import { promises as fs } from 'node:fs'
import path from 'node:path'

register(StyleDictionary)

/* The 'tokens-studio' group names with camelCase; our CSS is kebab
 * (--paper-2, --ink-soft, --menubar-h). Clone the group, swap the name
 * transform to name/kebab. */
const tsGroup = StyleDictionary.hooks.transformGroups['tokens-studio']
StyleDictionary.registerTransformGroup({
  name: 'tokens-studio-kebab',
  transforms: [...tsGroup.filter((t) => !t.startsWith('name/')), 'name/kebab'],
})

const ROOT = path.resolve(process.cwd())
const TOKENS_DIR = path.join(ROOT, 'tokens')
const OUT_DIR = path.join(ROOT, 'src/styles/generated')
const OUT_FILE = path.join(ROOT, 'src/styles/tokens.generated.css')

/* Final selector model. classic-dark also matches today's bare
 * [data-theme='dark'] so dark mode keeps working before the data-skin
 * attribute exists (introduced in Milestone B / store widening). */
const SELECTOR = {
  'classic-light': ":root,\n[data-skin='classic']",
  'classic-dark': "[data-theme='dark'],\n[data-skin='classic'][data-theme='dark']",
  medieval: "[data-skin='medieval']",
  underwater: "[data-skin='underwater']",
}

const themes = JSON.parse(await fs.readFile(path.join(TOKENS_DIR, '$themes.json'), 'utf8'))
await fs.mkdir(OUT_DIR, { recursive: true })

for (const theme of themes) {
  const sets = Object.entries(theme.selectedTokenSets).filter(([, v]) => v !== 'disabled')
  const source = sets.map(([s]) => path.join('tokens', `${s}.json`))
  const enabled = new Set(
    sets.filter(([, v]) => v === 'enabled').map(([s]) => path.resolve(TOKENS_DIR, `${s}.json`))
  )

  const sd = new StyleDictionary({
    source,
    preprocessors: ['tokens-studio'],
    usesDtcg: true,
    log: { verbosity: 'silent', warnings: 'disabled' },
    platforms: {
      css: {
        transformGroup: 'tokens-studio-kebab',
        buildPath: 'src/styles/generated/',
        files: [
          {
            destination: `${theme.id}.css`,
            format: 'css/variables',
            // emit only tokens that came from an `enabled` set
            filter: (token) => enabled.has(path.resolve(token.filePath)),
            options: {
              selector: SELECTOR[theme.id],
              usesDtcg: true,
              // var() only for references whose target is ALSO emitted here;
              // references to internal primitives resolve to literals
              outputReferences: outputReferencesFilter,
            },
          },
        ],
      },
    },
  })
  await sd.buildAllPlatforms()
}

// concatenate per-theme files in $themes order into one committed file
const header =
  '/* GENERATED by scripts/build-tokens.mjs from tokens/ — DO NOT EDIT.\n' +
  '   Run `npm run tokens:build` after editing tokens. */\n\n'
let out = header
for (const theme of themes) {
  const css = await fs.readFile(path.join(OUT_DIR, `${theme.id}.css`), 'utf8')
  out += css.trimEnd() + '\n\n'
}
await fs.writeFile(OUT_FILE, out)
console.log(`✓ wrote src/styles/tokens.generated.css (${themes.length} themes)`)
